backend: none
mysql:
  user: username
  pass: password1
  dbname: mydatabase
  host: localhost
  port: 3306
  tableprefix: neo_
language: en
commandaliases:
  neoban: [nban, ban]
  neounban: [nunban, unban]
  neotempban: [ntempban, tempban]
  neokick: [nkick, kick]
  neoinfo: [ninfo, baninfo]
  neoeditban: [neditban, editban]
broadcast:
  kick: GLOBAL
  ban: GLOBAL
  tempban: GLOBAL
  unban: GLOBAL