jail:
  server: ''
  unjail-server: ''
  afk-kick-delay: 60
  afk-kick-contains: afk

backend: none
mysql:
  user: username
  pass: password1
  database: mydatabase
  host: localhost
  port: 3306
  tableprefix: neo_
  connector: mariadb
language: en
commandaliases:
  neoban: [nban, ban]
  neounban: [nunban, unban]
  neotempban: [ntempban, tempban]
  neojail: [njail, jail]
  neounjail: [nunjail, unjail]
  neokick: [nkick, kick]
  neokickall: [nkickall, kickall]
  neoinfo: [ninfo, baninfo, jailinfo]
  neoeditentry: [neditentry, editentry, editjail, editban]
  neolog: [banlog]
broadcast:
  kick: GLOBAL
  kickall: GLOBAL
  kickallserver: SERVER
  ban: GLOBAL
  tempban: GLOBAL
  unban: GLOBAL
  jail: GLOBAL
  unjail: SENDER