package de.themoep.NeoBans.core;

import java.util.UUID;

/**
 * Created by Phoenix616 on 11.02.2015.
 */
public class BanEntry extends Entry {

    protected UUID banned;

    protected UUID issuer;

    protected String comment;
    
    protected int dbId = -1;

    public BanEntry(UUID banned, UUID issuer, String reason) {
        super(EntryType.BAN, reason);
        this.banned = banned;
        this.issuer = issuer;
        this.comment = "";
    }

    public BanEntry(UUID banned, UUID issuer, String reason, String comment, long time) {
        super(EntryType.BAN, reason, time);
        this.banned = banned;
        this.issuer = issuer;
        this.reason = reason;
        this.comment = comment;
    }

    /**
     * Get the UUID of the affected player
     * @return The UUID of the affected player
     */
    public UUID getBanned() {
        return banned;
    };

    /**
     * Get the UUID of the player that issued the entry
     * @return The UUID of the player issuing the entry
     */
    public UUID getIssuer() {
        return issuer;
    };


    /**
     * Get the comment to this ban
     * @return The ban comment as a string
     */
    public String getComment() {
        return comment;
    }

    /**
     * Set the ban id. This should get automatically generated by the database
     * @param dbId The auto incremented database table entry id; null if no database or not yet assigned
     */
    public void setDbId(int dbId) {
        this.dbId = dbId;
    }

    public int getDbId() {
        return dbId;
    }
}
